Scott day
SeniorDesign-Group9/initial-document pull request #28
Opened 2022-12-05 20:46 UTC by Caution2TheWind

2022-12-05 21:05 UTC, myhe01 approved these changes
LGTM

2022-12-05 21:09 UTC, NChitty requested changes

2022-12-05 21:09 UTC, NChitty commented on design-details/sensing.tex
Please remove all the reference links, and just send them to me in an excel spreadsheet or similar and I can create the references at the end of the document

2022-12-05 21:09 UTC, NChitty commented on design-details/sensing.tex
Remove references like this and just send me the link or reference formatted into title, author, date, etc.

2022-12-05 21:09 UTC, NChitty commented on design-details/sensing.tex
I can't approve this PR with placeholders inside

2022-12-05 21:09 UTC, NChitty commented on design-details/sensing.tex
reference

2022-12-05 21:09 UTC, NChitty commented on images/Untitled Diagram.drawio
> +<mxfile host="app.diagrams.net" modified="2022-09-15T12:23:42.599Z" agent="5.0 (Windows)" etag="mQtC2qX0FcSpJy2eUsW2" version="20.3.0" type="device"><diagram id="sM39jpTHVHrNeqXCZMDn" name="Page-1">7
What is this?

2022-12-06 01:20 UTC, NChitty approved these changes

2022-12-06 01:23 UTC, merged